### ISSUE TITLE
请教一下大佬，您的xapkInstaller项目面对多台手机连接到电脑的情况下。

### ISSUE THREAD

**Issue by Yesisyes** [adhu2018/adhu2018.github.io#1]
大佬，电脑连接了多台手机实体机的话。你的xapkInstaller有提供指定哪个手机装哪个XAPK文件的接口吗？例如我多线程模式下自动化操作多台手机。当使用xapkInstaller.exe安装XAPK文件发现好像是随机一个手机装进去的。

**Comment by adhu2018** [comment]
全部手机都会装的，可以尝试 https://github.com/d3xter-lab/xapkInstaller 。抱歉，不知道是以前设置的还是默认的，这个库下的issues提醒并没有开。
